### ISSUE TITLE
יש אפשרות שזה יפעל באונליין בלי התקנה על המחשב?

### ISSUE THREAD

**Issue by motel12** [Sivan22/ituria#4]
האם זה מורכב להעלות את זה לאתר שיהיה אפשר להשתמש בזה בלי להפעיל על המחשב?
זה משהו בתכנון או שזה מורכב?
תודה רבה!

**Comment by Sivan22** [comment]
זה בהחלט בתכנון, אבל אני לא יודע כמה זמן יקח.

בתאריך יום א׳, 8 בדצמ׳ 2024, 20:25, מאת motel12 ***@***.***>:

**Comment by motel12** [comment]
https://huggingface.co/spaces/sivan22/Ituria
תודה רבה!
