### ISSUE TITLE
כמה בעיות

### ISSUE THREAD

**Issue by YOSEFTT** [Sivan22/ituria#5]
א. האם יש אפשרות שהקוד מקור יעבוד עם OLLAMA? 
ב. למה בפתיחה [ע"י קוד המקור] אני מקבל שגיאה - There was an error while processing your request: Provider Claude not available כמובן התקנתי את כל החבילות הנדרשות.
ג. ע"י התוכנה הניידת, אני מקבל שגיאה: I encountered an error generating the answer: 2 validation errors for ChatRequest
format.literal['json']
Input should be 'json' [type=literal_error, input_value=", input_type=str]
For further information visit https://errors.pydantic.dev/2.10/v/literal_error
format.dict[str,any]
Input should be a valid dictionary [type=dict_type, input_value=", input_type=str]
For further information visit https://errors.pydantic.dev/2.10/v/dict_type
כמו ש @דאנציג כתב [ במתמחים טופ](https://mitmachim.top/topic/77639/%D7%94%D7%A1%D7%91%D7%A8-%D7%97%D7%99%D7%A4%D7%95%D7%A9-%D7%97%D7%9B%D7%9D-%D7%91%D7%90%D7%9E%D7%A6%D7%A2%D7%95%D7%AA-%D7%A1%D7%95%D7%9B%D7%9F-ai/49)
ד. האם יש אפשרות שהתוכנה תפעל על ה API של גרוק של המודל LLAMA?
ה. אם אני מבין נכון, הסרת את  ממשק המשתמש של האינטרנט, אז תעדכן את הקובץ README.

**Comment by Sivan22** [comment]
א. הוא כבר עובד עם ollama אם מותקן מודל בשם dictaLM
ב.צריך להכניס api בקובץ ini.
ג. זה לא באג שלי, צריך להתקין pip install -U ollama
ד. אני אבדוק. 
ה. עדכנתי.

**Comment by YOSEFTT** [comment]
א. ניסיתי וזה לא עובד לי, האם בדקת שזה באמת עובד על OLLAMA עם DICTALM?
ב. עם אני עובד עם OLLAMA איזה API אני צריך להכניס?
ג. אני מדבר על התוכנה הניידת, מה הקשר להתקין ספריות??? חוץ מזה שהתקנתי, ולא עזר.

**Comment by Y-PLONI** [comment]
@Sivan22 
האם תוכל לתת אפשרות לבחירת מודל באולמה? קשה לי עם ההגבלה הזו, כי אצלי זה נקרא:
`dictaLM:latest`

**Comment by sh5616107** [comment]
לי יש גם את בעיה ג' שציין @YOSEFTT השאלה שלי אם לשנות אצל ollama את השם של המודל מdictaLM לdictalm0.2 כפי שמופיע בתוכנה זה יעזור?
תודה

**Comment by Sivan22** [comment]
אני רוצה שהוא יציג את המודלים הקיימים במחשבהנוכחי ואפשר יהיה לבחור.

**Comment by Sivan22** [comment]
הכל תוקן בגרסה 2.0.
